<?php

return array(
    0 => 'Consumer Tech',
    1 => 'Animal Meat',
    2 => 'Coffee',
    3 => 'Tea',
    4 => 'Tobacco',
    5 => 'Superconductors',
    6 => 'Performance Enhancers',
    7 => 'Progenitor Cells',
    8 => 'Beryllium',
    9 => 'Gallium',
    10 => 'Gold',
    11 => 'Indium',
    12 => 'Palladium',
    13 => 'Silver',
    14 => 'Tantalum',
    15 => 'Uranium',
    16 => 'Advanced Catalysers',
    17 => 'Auto Fabricators',
    18 => 'Land Enrichment Systems',
    19 => 'Resonating Separators',
    20 => 'Crop Harvesters',
    21 => 'Marine Equipment',
    22 => 'NonLethal Weapon',
    23 => 'Personal Weapon',
    24 => 'Reactive Armour',
);